//! Enumerate candidate files for the text fixers.
//!
//! Two modes:
//! - `walk`: recursive directory walk under `root`, honouring `.gitignore`
//!   (plus `.git/info/exclude` and the global gitignore) and skipping a
//!   conservative deny-list of VCS/build directories.
//! - `tracked`: `git ls-files -z` from `root`; falls back to the walk if
//!   git is not available or the directory is not a repo.
//!
//! The gitignore filter matters because the fixers rewrite files in place and
//! exit non-zero on change: a build artifact regenerated by an earlier step of
//! the same `ops verify` run (e.g. `*.tsbuildinfo`) would otherwise be
//! "fixed" on every run, so verify could never pass. Ignore rules only apply
//! rules are honoured even without a `.git` directory (`require_git(false)`),
//! so a checked-out worktree without git installed behaves the same.

use std::path::{Path, PathBuf};
use std::process::Command;

use ignore::WalkBuilder;

const SKIP_DIRS: &[&str] = &[
    ".git",
    "target",
    "node_modules",
    "dist",
    "build",
    ".venv",
    "venv",
    "__pycache__",
    ".terraform",
];

pub fn discover(root: &Path, tracked_only: bool) -> std::io::Result<Vec<PathBuf>> {
    if tracked_only {
        if let Some(paths) = tracked_files(root) {
            return Ok(paths);
        }
    }
    walk(root)
}

fn walk(root: &Path) -> std::io::Result<Vec<PathBuf>> {
    // `hidden(false)` keeps dotfiles (`.ops.toml`, `.gitignore`, …) in scope;
    // only ignore rules and the deny-list remove entries. Filesystem errors on
    // individual entries stay silently skipped, as in the previous hand-rolled
    // walk.
    let walker = WalkBuilder::new(root)
        .hidden(false)
        .require_git(false)
        .filter_entry(|entry| {
            // depth 0 is `root` itself: never filter it, or a project living
            // in a directory literally named `build`/`dist` would scan empty.
            entry.depth() == 0
                || !entry.file_type().is_some_and(|t| t.is_dir())
                || !SKIP_DIRS
                    .iter()
                    .any(|d| *d == entry.file_name().to_string_lossy())
        })
        .build();
    let mut out = Vec::new();
    for entry in walker.flatten() {
        // `follow_links` is off, so symlinks surface as symlink entries and
        // are dropped here rather than being rewritten through.
        if entry.file_type().is_some_and(|t| t.is_file()) {
            out.push(entry.into_path());
        }
    }
    Ok(out)
}

fn tracked_files(root: &Path) -> Option<Vec<PathBuf>> {
    let output = Command::new("git")
        .arg("-C")
        .arg(root)
        .args(["ls-files", "-z"])
        .output()
        .ok()?;
    if !output.status.success() {
        return None;
    }
    let mut out = Vec::new();
    for chunk in output.stdout.split(|b| *b == 0) {
        if chunk.is_empty() {
            continue;
        }
        let rel = match std::str::from_utf8(chunk) {
            Ok(s) => s,
            Err(_) => continue,
        };
        out.push(root.join(rel));
    }
    Some(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn walk_skips_deny_listed_dirs() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        std::fs::write(root.join("keep.txt"), b"a").unwrap();
        std::fs::create_dir_all(root.join("target/sub")).unwrap();
        std::fs::write(root.join("target/sub/skip.txt"), b"a").unwrap();
        std::fs::create_dir_all(root.join("node_modules")).unwrap();
        std::fs::write(root.join("node_modules/skip.txt"), b"a").unwrap();

        let files = walk(root).unwrap();
        let names: Vec<String> = files
            .iter()
            .map(|p| p.file_name().unwrap().to_string_lossy().into_owned())
            .collect();
        assert!(names.contains(&"keep.txt".to_string()));
        assert!(!names.iter().any(|n| n == "skip.txt"));
    }

    #[test]
    fn walk_skips_gitignored_files() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        std::fs::write(root.join(".gitignore"), b"*.tsbuildinfo\ngenerated/\n").unwrap();
        std::fs::write(root.join("keep.ts"), b"a").unwrap();
        std::fs::write(root.join("tsconfig.app.tsbuildinfo"), b"{}").unwrap();
        std::fs::create_dir_all(root.join("generated")).unwrap();
        std::fs::write(root.join("generated/out.txt"), b"a").unwrap();

        let names: Vec<String> = walk(root)
            .unwrap()
            .iter()
            .map(|p| p.file_name().unwrap().to_string_lossy().into_owned())
            .collect();
        assert!(names.contains(&"keep.ts".to_string()));
        // dotfiles stay in scope; only ignore rules and the deny-list filter.
        assert!(names.contains(&".gitignore".to_string()));
        assert!(!names.iter().any(|n| n == "tsconfig.app.tsbuildinfo"));
        assert!(!names.iter().any(|n| n == "out.txt"));
    }

    #[test]
    fn walk_does_not_filter_the_root_itself() {
        let dir = tempfile::tempdir().unwrap();
        // root is named `build`, which the deny-list drops for subdirectories.
        let root = dir.path().join("build");
        std::fs::create_dir_all(&root).unwrap();
        std::fs::write(root.join("keep.txt"), b"a").unwrap();

        let files = walk(&root).unwrap();
        assert_eq!(files.len(), 1);
        assert!(files[0].ends_with("keep.txt"));
    }

    #[test]
    fn walk_descends_into_normal_subdirs() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        std::fs::create_dir_all(root.join("src/nested")).unwrap();
        std::fs::write(root.join("src/nested/deep.txt"), b"a").unwrap();
        let files = walk(root).unwrap();
        assert_eq!(files.len(), 1);
        assert!(files[0].ends_with("src/nested/deep.txt"));
    }
}
