//! Enumerate candidate files for the text fixers.
//!
//! Two modes:
//! - `walk`: recursive directory walk under `root`, honouring `.gitignore`
//!   (plus `.git/info/exclude` and the global gitignore) and skipping a
//!   conservative deny-list of VCS/build directories.
//! - `tracked`: `git ls-files -z` from `root`.
//!
//! The gitignore filter matters because the fixers rewrite files in place and
//! exit non-zero on change: a build artifact regenerated by an earlier step of
//! the same `ops verify` run (e.g. `*.tsbuildinfo`) would otherwise be
//! "fixed" on every run, so verify could never pass. Ignore rules are honoured
//! even without a `.git` directory (`require_git(false)`), so a checked-out
//! worktree without git installed behaves the same.
//!
//! # Symlink policy
//!
//! **Symlinks are out of scope for both modes.** Every candidate is filtered
//! through `is_candidate`, the single place that decides what a candidate is:
//! it uses [`std::fs::symlink_metadata`] (never `metadata`), so a link is
//! judged by the link itself and never by its target.
//!
//! This is not a nicety. The fixers rewrite in place, and a
//! repository-controlled symlink (`docs/config -> ../../../etc/app.conf`)
//! would otherwise have its *target* read, truncated and rewritten — a write
//! outside `root` driven by cloned repository content, on a path that runs
//! from a git hook. It also keeps a link to a FIFO or a device out of the
//! read path, where it would block or never reach EOF.
//!
//! Before this was centralised the two modes disagreed by accident: `walk`
//! dropped symlinks only because `ignore` reports them with a symlink file
//! type when `follow_links` is off, while `tracked` pushed every path
//! `git ls-files` printed. `walk`'s per-entry type test is kept as a cheap
//! pre-filter (it also removes directories without a second `stat`), but
//! `is_candidate` is the authority for both modes.
//!
//! # Path encoding
//!
//! On Unix a path is an arbitrary NUL-free byte sequence and `git ls-files -z`
//! emits those bytes verbatim, so tracked paths are rebuilt with
//! [`std::os::unix::ffi::OsStrExt::from_bytes`] — no UTF-8 validation, no
//! allocation, and no silent loss of a latin-1-named file. On other targets
//! git emits UTF-8; a path that still fails to decode there is dropped and
//! counted in [`Discovery::undecodable_paths`] so the caller reports it rather
//! than swallowing it.

use std::ffi::OsStr;
use std::fmt;
use std::io;
use std::path::{Path, PathBuf};
use std::process::Command;

use ignore::WalkBuilder;

const SKIP_DIRS: &[&str] = &[
    ".git",
    "target",
    "node_modules",
    "dist",
    "build",
    ".venv",
    "venv",
    "__pycache__",
    ".terraform",
];

/// Why a `tracked_only` run fell back to the full filesystem walk.
///
/// The fallback is legitimate, but it *widens the file set a destructive tool
/// operates on* — from "files git knows about" to "every non-ignored file,
/// including untracked ones". It is therefore carried out of discovery rather
/// than assumed: see [`Discovery::fallback`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Fallback {
    /// No `git` executable on `PATH`.
    GitUnavailable,
    /// git ran and reported that `root` is not inside a repository.
    NotARepository,
}

impl fmt::Display for Fallback {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::GitUnavailable => f.write_str("git is not installed"),
            Self::NotARepository => f.write_str("not a git repository"),
        }
    }
}

/// The candidate set, plus what had to be given up to produce it.
#[derive(Debug, Default)]
pub struct Discovery {
    /// Regular files to consider, in discovery order.
    pub files: Vec<PathBuf>,
    /// `Some` when `tracked_only` was requested and could not be honoured.
    /// Always `None` for a walk-mode run.
    pub fallback: Option<Fallback>,
    /// Tracked paths dropped because their bytes could not be decoded into a
    /// path on this target. Always 0 on Unix, where no decoding happens.
    pub undecodable_paths: usize,
    /// Directories or entries the walk could not traverse, already rendered.
    ///
    /// The walk cannot say how many files each one hid, so these are not
    /// counted anywhere — but an unreadable directory contributing zero files
    /// to a gate that reports "clean" is exactly the fail-open this crate is
    /// trying to close, so the caller is told.
    pub walk_errors: Vec<String>,
}

/// What `git ls-files` had to say.
enum Tracked {
    /// The tracked paths, and how many printed paths could not be decoded.
    Files {
        files: Vec<PathBuf>,
        undecodable: usize,
    },
    /// git ran, and reported that this is not a repository.
    NotARepository,
    /// No `git` executable on `PATH`.
    GitUnavailable,
}

/// Enumerate the files the fixers may rewrite under `root`.
///
/// `tracked_only` asks for the git index rather than the filesystem. It falls
/// back to the full walk for the two outcomes that mean "there is no index to
/// read" — git is not installed, or `root` is not a repository — and records
/// which one fired in [`Discovery::fallback`]. **Every other git failure is an
/// error.** From the caller's side a broken repository is indistinguishable
/// from a working one, so collapsing it into the fallback would silently
/// change which of the user's files get rewritten. `dubious ownership` (a repo
/// checked out under another uid — the default in containers and on shared
/// build agents) is exactly that case: git exits non-zero on a directory that
/// *is* a repo, and a single `None` return used to turn that into "rewrite
/// every untracked scratch file too".
///
/// # Errors
///
/// If the filesystem walk fails, or if `git ls-files` fails for any reason
/// other than the two fallback cases above.
pub fn discover(root: &Path, tracked_only: bool) -> io::Result<Discovery> {
    if tracked_only {
        match tracked_files(root)? {
            Tracked::Files {
                mut files,
                undecodable,
            } => {
                retain_regular_files(&mut files);
                return Ok(Discovery {
                    files,
                    fallback: None,
                    undecodable_paths: undecodable,
                    walk_errors: Vec::new(),
                });
            }
            Tracked::NotARepository => return walked(root, Some(Fallback::NotARepository)),
            Tracked::GitUnavailable => return walked(root, Some(Fallback::GitUnavailable)),
        }
    }
    walked(root, None)
}

fn walked(root: &Path, fallback: Option<Fallback>) -> io::Result<Discovery> {
    let (files, walk_errors) = walk(root)?;
    Ok(Discovery {
        files,
        fallback,
        undecodable_paths: 0,
        walk_errors,
    })
}

/// The one place that decides whether a discovered path is a candidate.
///
/// `symlink_metadata` rather than `metadata`: a symlink must be judged by the
/// link, not by whatever it points at. See the module-level symlink policy.
///
/// A path this cannot stat at all — gone from the worktree, or in a directory
/// the process cannot search — is **kept**, not dropped. Discovery removes
/// only what it positively identified as the wrong *type*; deciding what a
/// vanished or unreachable path means belongs to the consumer, which is also
/// the layer that can report it. Dropping it here would put the path straight
/// back into the class of files nobody is told about.
fn is_candidate(path: &Path) -> bool {
    std::fs::symlink_metadata(path).map_or(true, |md| md.file_type().is_file())
}

fn retain_regular_files(files: &mut Vec<PathBuf>) {
    files.retain(|p| is_candidate(p));
}

/// Walk `root`, returning the candidate files and a rendered line for every
/// entry the walk could not traverse.
///
/// Per-entry errors used to be dropped by a bare `.flatten()`. An unreadable
/// directory then contributed zero files in silence, which on a gate reads as
/// "nothing to fix here".
// Returns `io::Result` to match `discover`'s signature and the tracked-file
// walker it alternates with.
#[allow(clippy::unnecessary_wraps)]
fn walk(root: &Path) -> io::Result<(Vec<PathBuf>, Vec<String>)> {
    // `hidden(false)` keeps dotfiles (`.ops.toml`, `.gitignore`, …) in scope;
    // only ignore rules and the deny-list remove entries. Filesystem errors on
    // individual entries stay silently skipped, as in the previous hand-rolled
    // walk.
    let walker = WalkBuilder::new(root)
        .hidden(false)
        .require_git(false)
        .filter_entry(|entry| {
            // depth 0 is `root` itself: never filter it, or a project living
            // in a directory literally named `build`/`dist` would scan empty.
            entry.depth() == 0
                || !entry.file_type().is_some_and(|t| t.is_dir())
                || !SKIP_DIRS
                    .iter()
                    .any(|d| *d == entry.file_name().to_string_lossy())
        })
        .build();
    let mut out = Vec::new();
    let mut errors = Vec::new();
    for entry in walker {
        match entry {
            Ok(entry) => {
                if entry.file_type().is_some_and(|t| t.is_file()) {
                    out.push(entry.into_path());
                }
            }
            Err(e) => errors.push(e.to_string()),
        }
    }
    retain_regular_files(&mut out);
    Ok((out, errors))
}

fn tracked_files(root: &Path) -> io::Result<Tracked> {
    let output = match Command::new("git")
        .arg("-C")
        .arg(root)
        .args(["ls-files", "-z"])
        // The `not a git repository` match below reads git's *stderr*, which
        // git localises. Pin the locale to C so a developer running under a
        // translated locale still lands on `Fallback::NotARepository` instead
        // of the hard-error path.
        .env("LC_ALL", "C")
        .env("LANGUAGE", "C")
        .output()
    {
        Ok(output) => output,
        Err(e) if e.kind() == io::ErrorKind::NotFound => return Ok(Tracked::GitUnavailable),
        Err(e) => return Err(e),
    };

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        if stderr.contains("not a git repository") {
            return Ok(Tracked::NotARepository);
        }
        return Err(io::Error::other(format!(
            "git ls-files in {} failed ({}): {}",
            root.display(),
            output.status,
            stderr.trim()
        )));
    }

    let mut files = Vec::new();
    let mut undecodable = 0usize;
    for chunk in output.stdout.split(|b| *b == 0) {
        if chunk.is_empty() {
            continue;
        }
        push_decoded(&mut files, &mut undecodable, root, chunk);
    }
    Ok(Tracked::Files { files, undecodable })
}

#[cfg(unix)]
fn push_decoded(files: &mut Vec<PathBuf>, _undecodable: &mut usize, root: &Path, chunk: &[u8]) {
    use std::os::unix::ffi::OsStrExt;
    // Lossless, and infallible: on Unix a path *is* bytes, so there is nothing
    // to validate and a latin-1-named file survives instead of being silently
    // dropped. Nothing can be undecodable here.
    files.push(root.join(OsStr::from_bytes(chunk)));
}

#[cfg(not(unix))]
fn push_decoded(files: &mut Vec<PathBuf>, undecodable: &mut usize, root: &Path, chunk: &[u8]) {
    // git emits UTF-8 on Windows; anything else is a genuine surprise, so it
    // is dropped and counted rather than guessed at.
    match std::str::from_utf8(chunk) {
        Ok(rel) => files.push(root.join(rel)),
        // The count is bounded by the number of NUL-separated chunks in one
        // `git ls-files` output, so it cannot saturate a `usize`.
        Err(_) => *undecodable = undecodable.saturating_add(1),
    }
}

#[cfg(test)]
mod tests;
