[output]
theme = "compact"
#theme = "classic"

[commands.install]
program = "cargo"
args = ["install", "--path", "crates/cli", "--force", "--all-features"]

[commands.run-before-commit]
commands = ["verify"]
fail_fast = true
help = "Run run-before-commit checks before committing"

[commands.run-before-push]
commands = ["qa"]
fail_fast = true
help = "Run run-before-push checks before pushing"
