[output]
theme = "compact"
#theme = "classic"

[commands.install]
program = "cargo"
args = ["install", "--path", "crates/cli", "--force", "--all-features"]

[commands.deps]
program = "ops"
args = ["deps"]
help = "Check dependencies, advisories, licenses, bans and sources in the workspace"

[commands.pre-commit]
commands = ["deps", "verify"]
fail_fast = true
parallel = true
help = "Check dependencies, advisories, licenses, bans and sources also run verify (build, clippy, test) commands before committing"
