[workspace]
publish = false
changelog_update = true
# Make it a single changelog at repo root (not per-crate)
changelog_path = "./CHANGELOG.md"
changelog_config = "cliff.toml"
git_release_enable = false

[[package]]
name = "cargo-ops"
publish = false
