[package]
name = "ops-rust-foundation"
publish = false
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ops-core = { workspace = true }
ops-cargo-toml = { workspace = true }
ops-about-rust = { workspace = true }
anyhow = { workspace = true }
indexmap = { workspace = true }
toml = { workspace = true }
toml_edit = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
