# Default commands for Go stack.

[commands.fmt]
program = "go"
args = ["fmt", "./..."]
help = "Format all code"
category = "Code Quality"

[commands.vet]
program = "go"
args = ["vet", "./..."]
aliases = ["lint"]
help = "Vet all packages"
category = "Code Quality"

[commands.build]
program = "go"
args = ["build", "./..."]
help = "Build all packages"
category = "Build"

[commands.test]
program = "go"
args = ["test", "./..."]
help = "Run all tests"
category = "Code Quality"

[commands.clean]
program = "go"
args = ["clean", "./..."]
help = "Remove build artifacts"
category = "Build"

[commands.verify]
commands = ["fmt", "build"]
parallel = false
fail_fast = true
help = "Run fmt, build"
category = "Code Quality"

[commands.qa]
commands = ["test", "vet"]
parallel = false
fail_fast = true
help = "Run test, vet"
category = "Code Quality"
