name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTC_WRAPPER: sccache

jobs:
  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
          rustflags: ""
      - uses: mozilla-actions/sccache-action@v0.0.9
      - name: cargo fmt --all
        run: cargo fmt --all

  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ""
      - uses: mozilla-actions/sccache-action@v0.0.9
      - name: cargo check --all --all-features
        run: cargo check --all --all-features

  clippy:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
          rustflags: ""
      - uses: mozilla-actions/sccache-action@v0.0.9
      - name: cargo clippy --all --all-features -- -D warnings
        run: cargo clippy --all --all-features -- -D warnings

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ""
      - uses: mozilla-actions/sccache-action@v0.0.9
      - name: cargo build --all --all-features
        run: cargo build --all --all-features

  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_VERBOSE: true
      OPS_LOG_LEVEL: debug
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ""
      - uses: mozilla-actions/sccache-action@v0.0.9
      - name: cargo test --all --all-features -- --ignored
        run: cargo test --all --all-features -- --ignored

  deps:
    name: Deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ""
      - uses: mozilla-actions/sccache-action@v0.0.9
      - name: Install cargo-edit and cargo-deny
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-edit,cargo-deny
      - name: Install ops
        uses: jaxxstorm/action-install-gh-release@v1
        with:
          repo: rsvalerio/ops
      - name: ops --raw deps
        run: cargo deny check

  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ""
      - uses: mozilla-actions/sccache-action@v0.0.9
      - name: cargo install --path crates/cli --force --all-features
        run: cargo install --path crates/cli --force --all-features
